site_name: UL HPC Tutorials
pages:
- Home: 'index.md'
- Latest HPC School: 'hpc-school.md'
- Setup:
  - Overview:       'setup/index.md'
  - Pre-Requisites: 'setup/preliminaries.md'
  - Installation:   'setup/install.md'
- Basic Tutorials:
  - Getting Started: 'beginners/index.md'
  - HPC workflow with sequential jobs: 'basic/sequential_jobs/index.md'
  - Prototyping with Python: 'python/basics/index.md'
- Scheduling:
  - Job scheduling with SLURM: 'scheduling/advanced/index.md'
- Tools / Software management:
  - Easybuild: 'tools/easybuild/index.md'
#  - RESIF:     'tools/resif/index.md'
- Debugging and Profiling:
  - Efficient Debugging:     'debugging/basics/index.md'
  - Performance engineering: 'debugging/advanced/index.md'
- Parallel MPI and/or OpenMP:
  - Overview: 'parallel/basics/index.md'
  - OSU Micro-benchmarks: 'parallel/mpi/OSU_MicroBenchmarks/index.md'
  - High Perf. Linpack (HPL): 'parallel/mpi/HPL/index.md'
  - High Perf. Conjugate Gradient (HPCG): 'parallel/hybrid/HPCG/index.md'
- Python:
  - Prototyping with Python: 'python/basics/index.md'
  - Jupyter and Celery: 'python/advanced/index.md'
- Mathematics:
  - MATLAB: 'maths/matlab/basics/index.md'
  - MATLAB (advanced): 'maths/matlab/advanced/index.md'
  - R - statistical computing: 'maths/R/index.md'
- Bioinformatics:
  - Running bioinformatics software: 'bio/basics/index.md'
  - Galaxy: 'bio/galaxy/index.md'
- CFD/MD/Chemistry:
   - Advanced Parallel execution: 'multiphysics/index.md'
- Big Data:
  - Big Data Application Over Hadoop and Spark: 'bigdata/index.md'
- Containers:
  - Singularity: 'containers/singularity/index.md'
- Virtualization:
   - Vagrant: 'virtualization/vagrant/index.md'
   - Grid5000 - Automatic VM deployment with VM5K: 'virtualization/vm5k/index.md'
- Misc:
  - Reproducible Research: 'misc/reproducible-research/index.md'
# - Advanced topics:
#   - Advanced workflows on sequential jobs management: 'advanced/advanced_workflows/README.md'
- Documentation (RTFD): 'rtfd.md'
- Contributing: 'contributing.md'
- Contacts: 'contacts.md'
theme: readthedocs
